### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by marcoah** [paypronl/paypro-php#4]
I looking for the documentation for this version. 
Mainly, what is the difference between this version and 1.0?
Is there documentation somewhere? Which one do you recommend implementing? I am implementing the 1.0 library in Laravel

**Comment by paypro-leon** [comment]
This API library is for the new PayPro API which is still in closed beta. You can request access to the new API by mailing support@paypro.nl. 

Documentation (still work in progress) you can find on: https://docs.paypro.nl and https://paypro-api.redoc.ly

For the old API you can use: https://github.com/paypronl/paypro-php-v1

As for which version to use, if you are building a completely new integration it might be interesting to use the new API as that will be the way forward.

**Comment by marcoah** [comment]
Thanks!! i will check out
